name: Node.js CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm ci
      
      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Build
        run: |
          npm run build
          cp dist/index.html dist/404.html
          cp favicon.ico dist/

      - name: Run E2E tests
        run: npm run test
        env:
          HEADLESS: true
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: howmuchmore.xyz
        
