name: Node.js CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          BASE_URL: "https://howmuchmore.xyz/"

      - run: npm ci
      - name: Test
        run: npm test
        env:
          HEADLESS: true
      - name: Lint
        run: npm run lint
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: howmuchmore.xyz
        
